### ISSUE TITLE
ソフトウェア使用許諾を開くとクラッシュ

### ISSUE THREAD

**Issue by ghost** [griffin-stewie/CSNFloatingHeaderViewFlowLayout#1]
オープンソース、EULAも同じ。

**Comment by tkmymzkymh** [comment]
勘違いでした。問題ありません。

**Comment by ghost** [comment]
I'm so sorry that I posted my issue into your repo by mistake... 
I don't know how to delete an unnecessary issue, so please ignore this...(or I would appreciate it if you delete it if possible)

**Comment by griffin-stewie** [comment]
@tkmymzkymh
never mind !
